version: '3.9'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /app
    volumes:
      - ./api/api:/app
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: dotnet watch run --urls http://0.0.0.0:8080